### ISSUE TITLE
Error: region not found for name: me-central-1

### ISSUE THREAD

**Issue by markandersontrocme** [terraform-aws-modules/terraform-aws-pricing#10]
## Description

Tried using the module, copied the example from [here](https://github.com/terraform-aws-modules/terraform-aws-pricing/blob/v1.2.0/examples/pricing-resources/main.tf). When running terraform plan I get this error

```
Error: region not found for name "me-central-1"
│ 
│   with module.eks_cluster.module.pricing.data.aws_region.one["me-central-1"],
│   on .terraform/modules/eks_cluster.pricing/modules/pricing/regions.tf line 5, in data "aws_region" "one":
│    5: data "aws_region" "one" {
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 1.3.1

- Terraform version: 1.1.6

- Provider version(s):  provider registry.terraform.io/hashicorp/aws v4.27.0

## Reproduction Code [Required]
```
module "pricing" {
  source  = "terraform-aws-modules/pricing/aws//modules/pricing"
  version = "1.3.1"

  debug_output = true

  resources = {
    "aws_instance.this" = {
      instanceType = "t3.large"
      location     = "us-east-1"
    }
  }
}
```

## Expected behavior

Looking to `pricing_per_resources`

## Actual behavior

Getting an error: `Error: region not found for name "me-central-1"`

## Additional context

I fixed this previously with this PR: https://github.com/terraform-aws-modules/terraform-aws-pricing/pull/6 I will do it again but for `me-central-1`

**Comment by antonbabenko** [comment]
> Note that AWS provider should always be set to us-east-1 or ap-south-1 region.

AWS Pricing service is available just in 2 regions - https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-pelong.html#pe-endpoint

---

Probably, there should be another PR similar to #6. Feel free to make it if you are using this module.
