### ISSUE TITLE
Error: region not found for name "eu-central-2"

### ISSUE THREAD

**Issue by markandersontrocme** [terraform-aws-modules/terraform-aws-pricing#14]
## Description

Tried using the module, copied the example from [here](https://github.com/terraform-aws-modules/terraform-aws-pricing/blob/v1.2.0/examples/pricing-resources/main.tf). When running terraform plan I get this error

```
│ Error: finding Region by name
│
│   with module.eks_cluster.module.pricing.data.aws_region.one["eu-central-2"],
│   on .terraform/modules/eks_cluster.pricing/modules/pricing/regions.tf line 5, in data "aws_region" "one":
│    5: data "aws_region" "one" {
│
│ region not found for name "eu-central-2"
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 2.0.0

- Terraform version:

Terraform v1.1.6
- Provider version(s):

+ provider registry.terraform.io/hashicorp/aws v4.38.0
## Reproduction Code [Required]

```
module "pricing" {
  source  = "terraform-aws-modules/pricing/aws//modules/pricing"
  version = "2.0.0"

  debug_output = true

  resources = {
    "aws_instance.this" = {
      instanceType = "t3.large"
      location     = "us-east-1"
    }
  }
}
```

## Expected behavior

Looking to pricing_per_resources
## Actual behavior

Getting an error: `region not found for name "eu-central-2"`
## Additional context

I have submitted 2 PRs in the past for fixing this for other regions, is there a more permanent solution? I tried using `  skip_region_validation = true` but doesn't seem to work...

**Comment by antonbabenko** [comment]
There can be a more universal solution involving the automatic generation of region maps values (like [this one](https://github.com/terraform-aws-modules/terraform-aws-pricing/blob/master/modules/pricing/filters.tf#L266-L292)) where keys are outputs of the [`aws_regions` data-source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/regions).

I didn't try it, but it seems to work and is more flexible.

**Comment by markandersontrocme** [comment]
I was able to fix it by making `all_regions` a variable and allowing the user to set it to `false`: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/regions#all_regions

I have a PR I will send soon if that works?

```
variable "query_all_regions" {
  description = "If true the source will query all regions regardless of availability"
  type        = bool
  default     = true
}
```

**Comment by antonbabenko** [comment]
Cool. The only thing I am a bit worried about is potential inconsistency in values across regions (e.g. there is "APE1-NatGateway-Hours", but for some regions there can be weird exceptions). This means we need to have a way to override values. I am not saying that this is a problem already, but it can be an issue.
