### ISSUE TITLE
Error: finding region by name

### ISSUE THREAD

**Issue by flavienbwk** [terraform-aws-modules/terraform-aws-pricing#22]
## Description

I try to use this module this way : 

```
module "pricing" {
    source = "terraform-aws-modules/pricing/aws//modules/pricing"

    resources = {
        "aws_instance.machine_1" = {
            instanceType = "c5a.xlarge"
            location     = "eu-central-1"
        }
    }
}
```

But get the following error : 

```
╷
│ Error: finding Region by name
│ 
│   with module.pricing.data.aws_region.one["il-central-1"],
│   on .terraform/modules/pricing/modules/pricing/regions.tf line 5, in data "aws_region" "one":
│    5: data "aws_region" "one" {
│ 
│ region not found for name "il-central-1"
╵
```

Am I using this module wrong ?

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version : terraform-aws-modules/pricing/aws//modules/pricing
- Terraform version: 1.5.6 (linux_amd64)
- Provider version(s): 1.5.6 (linux_amd64)

**Comment by antonbabenko** [comment]
Please make sure you use Terraform AWS provider version where all AWS regions are supported. In the case of `il-central-1` region, you need to use Terraform AWS provider version 5.12.0 or newer (see [their CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5120-august-10-2023)).
