### ISSUE TITLE
Updates to readme

### ISSUE THREAD

**Issue by greenozon** [terraform-aws-modules/terraform-aws-pricing#24]
Minor ticket to actualize readme page

current readme states:

```
Set AWS provider's region to us-east-1 or sa-east-1 when using [modules/pricing](https://github.com/terraform-aws-modules/terraform-aws-pricing/tree/master/modules/pricing) because AWS Pricing service is only available in these regions.
```

1) there is no region as `sa-east-1`  as stated in the readme
I believe this should be `ap-south-1`

2) current list of AWS regions that supports pricing querying is as follows:

▶  $ aws pricing describe-services --region us-east-1
▶  $ aws pricing describe-services --region eu-central-1
▶  $ aws pricing describe-services --region ap-south-1

it means +1 new region:  `eu-central-1`

The idea is to update readme and make it up-to-date

thanks

**Comment by greenozon** [comment]
hi @antonbabenko   hwdy!
any chance to review above micro PR please?

Glory to Ukraine!

**Comment by greenozon** [comment]
@antonbabenko  are you available to review this minor change please?

**Comment by antonbabenko** [comment]
Thanks, @greenozon !
