### ISSUE TITLE
pricing for remote state files

### ISSUE THREAD

**Issue by hemzet** [terraform-aws-modules/terraform-aws-pricing#3]
Hi,
Can you provide an example of how to work with remote state files for the pricing module, please? 
The remote state files need credentials so cannot be accessed simply via aws_s3_bucket_object. And as the S3 bucket is private, data http requests fail as well.
Any recommendation on how to deal with this scenario is much appreciated.
Thank you

**Comment by antonbabenko** [comment]
Hi! You should copy it from the remote state location and then pass it as an argument to this module (see [this example](https://github.com/terraform-aws-modules/terraform-aws-pricing/blob/master/examples/complete/main.tf#L12)).

Here is how you can do this using `curl` from Terraform - https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/notification/main.tf#L16-L33

**Comment by alko89** [comment]
This is really not a good way of doing it IMO. This means you have to download the state before the price, which means you have to do in two terraform modules. One to download the state and another to get the price. It would be a huge improvement to be able to do this in one go.

I tried using http module, but seems to not work as expected:

```
data "http" "example" {
  url = local.state_url

  request_headers = {
    Accept = "application/json"
    Authorization = "Basic ${local.base_auth}"
  }
}

module "pricing" {
  source = "terraform-aws-modules/pricing/aws//modules/pricing"

  aws_default_region = var.region

  content = data.http.example.body
}
```

However for some reason this doesn't work:
Invalid value for "inputMap" parameter: must have map or object type. I also tried encoding json body, but no luck.

**Comment by antonbabenko** [comment]
@Alko89 This is partially related to this open issue - https://github.com/hashicorp/terraform/issues/4149 . Unfortunately, there is no easy solution that I am aware of.
